#!/usr/bin/env ruby
require 'cljd/client'
require 'json'

if ARGV.length != 1
  $stderr.puts "Usage: #{$0} WORD-TO-SEARCH"
  exit 1
end
word = ARGV[0]
with_cljd_client do |c|
  c.eval("(-main #{word.to_json})", ns = 'mwdict.core')
end.each do |r|
  print r['out']
  $stderr.print r['err']
end
