#!/usr/bin/env node
"use strict";

var fs          = require('fs'),
    nreplClient = require('nrepl-client'),
    os          = require('os'),
    path        = require('path'),
    Q           = require('q'),
    util        = require('util');

if (process.argv.length != 3) {
    console.error("Usage: %s WORD-TO-SEARCH", process.argv[1]);
    process.exit(1);
}
var word = process.argv[2];
var nreplPortFile = path.join(os.homedir(), '.clj-center-nrepl-port');
var port = fs.readFileSync(nreplPortFile, 'utf8');
var conn = nreplClient.connect({port: port});
Q.ninvoke(conn, 'once', 'connect').then(function () {
    var code = util.format('(-main %s)', JSON.stringify(word));
    return Q.ninvoke(conn, 'eval', code, 'mwdict.core');
}).then(function (results) {
    results.forEach(function (result) {
        if (result.out) process.stdout.write(result.out);
        if (result.err) {
            process.stderr.write(result.err);
            process.exitCode = 1;
        }
    });
}).fin(function () {
    conn.end();
}).done();
